/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.homepisec.sensor.rest.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.homepisec.sensor.rest.client.model.CountdownStatus;
import org.homepisec.sensor.rest.client.model.TriggerStatus;

/**
 * AlarmStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-03T20:44:31.883+02:00")
public class AlarmStatus {
  @JsonProperty("countdown")
  private CountdownStatus countdown = null;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    DISARMED("DISARMED"),
    
    ARMED("ARMED"),
    
    COUNTDOWN("COUNTDOWN"),
    
    TRIGGERED("TRIGGERED");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String text) {
      for (StateEnum b : StateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("state")
  private StateEnum state = null;

  @JsonProperty("trigger")
  private TriggerStatus trigger = null;

  public AlarmStatus countdown(CountdownStatus countdown) {
    this.countdown = countdown;
    return this;
  }

   /**
   * Get countdown
   * @return countdown
  **/
  @ApiModelProperty(value = "")
  public CountdownStatus getCountdown() {
    return countdown;
  }

  public void setCountdown(CountdownStatus countdown) {
    this.countdown = countdown;
  }

  public AlarmStatus state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(required = true, value = "")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public AlarmStatus trigger(TriggerStatus trigger) {
    this.trigger = trigger;
    return this;
  }

   /**
   * Get trigger
   * @return trigger
  **/
  @ApiModelProperty(value = "")
  public TriggerStatus getTrigger() {
    return trigger;
  }

  public void setTrigger(TriggerStatus trigger) {
    this.trigger = trigger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlarmStatus alarmStatus = (AlarmStatus) o;
    return Objects.equals(this.countdown, alarmStatus.countdown) &&
        Objects.equals(this.state, alarmStatus.state) &&
        Objects.equals(this.trigger, alarmStatus.trigger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countdown, state, trigger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlarmStatus {\n");
    
    sb.append("    countdown: ").append(toIndentedString(countdown)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    trigger: ").append(toIndentedString(trigger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

