/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.homepisec.sensor.rest.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.homepisec.sensor.rest.client.model.DeviceReading;

/**
 * EventDeviceReading
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-31T18:03:50.888+02:00")
public class EventDeviceReading {
  @JsonProperty("payload")
  private List<DeviceReading> payload = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    DEVICE_READ("DEVICE_READ"),
    
    ALARM_DISARM("ALARM_DISARM"),
    
    ALARM_ARM("ALARM_ARM"),
    
    ALARM_COUNTDOWN("ALARM_COUNTDOWN"),
    
    ALARM_TRIGGER("ALARM_TRIGGER");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("type")
  private TypeEnum type = null;

  public EventDeviceReading payload(List<DeviceReading> payload) {
    this.payload = payload;
    return this;
  }

  public EventDeviceReading addPayloadItem(DeviceReading payloadItem) {
    if (this.payload == null) {
      this.payload = new ArrayList<DeviceReading>();
    }
    this.payload.add(payloadItem);
    return this;
  }

   /**
   * Get payload
   * @return payload
  **/
  @ApiModelProperty(value = "")
  public List<DeviceReading> getPayload() {
    return payload;
  }

  public void setPayload(List<DeviceReading> payload) {
    this.payload = payload;
  }

  public EventDeviceReading type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventDeviceReading eventDeviceReading = (EventDeviceReading) o;
    return Objects.equals(this.payload, eventDeviceReading.payload) &&
        Objects.equals(this.type, eventDeviceReading.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payload, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventDeviceReading {\n");
    
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

