/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.homepisec.control.rest.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DeviceGpio
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-20T11:09:27.770+02:00")
public class DeviceGpio {
  @JsonProperty("gpio")
  private Integer gpio = null;

  @JsonProperty("id")
  private String id = null;

  public DeviceGpio gpio(Integer gpio) {
    this.gpio = gpio;
    return this;
  }

   /**
   * Get gpio
   * @return gpio
  **/
  @ApiModelProperty(value = "")
  public Integer getGpio() {
    return gpio;
  }

  public void setGpio(Integer gpio) {
    this.gpio = gpio;
  }

  public DeviceGpio id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceGpio deviceGpio = (DeviceGpio) o;
    return Objects.equals(this.gpio, deviceGpio.gpio) &&
        Objects.equals(this.id, deviceGpio.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gpio, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceGpio {\n");
    
    sb.append("    gpio: ").append(toIndentedString(gpio)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

