/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.homepisec.android.homepisecapp.control.rest.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.homepisec.android.homepisecapp.control.rest.client.model.Device;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * DeviceReading
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-04T23:34:34.549+01:00")
public class DeviceReading implements Parcelable {
  @SerializedName("device")
  private Device device = null;

  @SerializedName("value")
  private String value = null;

  public DeviceReading device(Device device) {
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  @ApiModelProperty(value = "")
  public Device getDevice() {
    return device;
  }

  public void setDevice(Device device) {
    this.device = device;
  }

  public DeviceReading value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceReading deviceReading = (DeviceReading) o;
    return Objects.equals(this.device, deviceReading.device) &&
        Objects.equals(this.value, deviceReading.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(device, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceReading {\n");
    
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
  public void writeToParcel(Parcel out, int flags) {
     
    out.writeValue(device);

    out.writeValue(value);
  }

  public DeviceReading() {
    super();
  }

  DeviceReading(Parcel in) {
    
    device = (Device)in.readValue(Device.class.getClassLoader());
    value = (String)in.readValue(null);
  }
  
  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<DeviceReading> CREATOR = new Parcelable.Creator<DeviceReading>() {
    public DeviceReading createFromParcel(Parcel in) {
      return new DeviceReading(in);
    }
    public DeviceReading[] newArray(int size) {
      return new DeviceReading[size];
    }
  };
}

